### PR TITLE
Wrong start and end of entities due to missing offset

### PR DESCRIPTION
**Pull request by cristinacaputo**
The current code in the interpreters folders: mitie_interpreter_utils.py gives an incorrect result for the following made up example in the restaurant data:

`I am looking for northern food in the north part of town`

I used this example because it illustrates the point, the `location` `north` entity has a wrong start and end - and overlaps with the `northern` `cuisine` entity.

Before the change:
```
{
    "confidence": 0.6449555829969771,
    "entities": [
        {
            "end": 25,
            "entity": "cuisine",
            "start": 17,
            "value": "northern"
        },
        {
            "end": 30,
            "entity": "cuisine",
            "start": 26,
            "value": "food"
        },
        {
            "end": 22,
            "entity": "location",
            "start": 17,
            "value": "north"
        }
    ],
    "intent": "restaurant_search",
    "text": "I am looking for northern food in the north part of town"
}

```

After the change:

```
{
    "confidence": 0.6449555829969771,
    "entities": [
        {
            "end": 25,
            "entity": "cuisine",
            "start": 17,
            "value": "northern"
        },
        {
            "end": 30,
            "entity": "cuisine",
            "start": 26,
            "value": "food"
        },
        {
            "end": 43,
            "entity": "location",
            "start": 38,
            "value": "north"
        }
    ],
    "intent": "restaurant_search",
    "text": "I am looking for northern food in the north part of town"
}
```
The change seems to fix this issue. I have tested it for several other cases and it works.

### CODE REVIEW

**Comment by tmbo** [comment]
Thanks a lot for your contribution @cristinacaputo :+1:

**Comment by amn41** [comment]
A question and a comment: 

-  why was the `re.escape` removed? Doesn't this mean we will fail to find entities containing `?/\&` and other regex special characters? 

-  we already solved this in #158 - must be a merge issue that caused it to reappear. that's frustrating. We had a test case for this as well but that also got lost

**Comment by tmbo** [comment]
The missing `re.escape` is my bad, should have noticed that when reviewing. It's already fixed.

The test case is still present and wasn't lost:
https://github.com/golastmile/rasa_nlu/blob/master/_pytest/test_tokenizers.py#L27 (was added in last PR), the nothern food town example should be added as well, you are right.

**Comment by tmbo** [comment]
@amn41 Oh, I just noticed something, it wasn't a regression of the previously valid code, rather this code is duplicated:
- https://github.com/golastmile/rasa_nlu/blob/master/src/tokenizers/mitie_tokenizer.py#L16 (the one fixed in this PR)
- https://github.com/golastmile/rasa_nlu/blob/master/src/interpreters/mitie_interpreter_utils.py#L9 (version in interpreter, that already contains the offset...)

**Comment by amn41** [comment]
Ah! good catch! :)

**Pull request merged**
