### PR TITLE
Dockerize application

### PR DESCRIPTION
**Pull request by phildionne**
This is a work in progress.

I'm not a python nor a docker expert, so consider this pr like a first take on dockerizing the project.

*Questions*
- What's the correct order for running `pip install -r requirements.txt` and `python setup.py install` ?
- `ENTRYPOINT` the command fails with `no module rasa_nlu`. No idea why.

Run it like this: `docker run -it --rm rasa_nlu`

### CODE REVIEW

**Comment by tmbo** [comment]
As far as I remember, `pip install -r requirements.txt` is not required for deployment and should only contain development dependencies. Running the `setup.py` should be sufficient.

@normanrz care to glance at the docker file?

**Comment by plauto** [comment]
looks great! The fix @normanrz propose will work; moreover u could also include a CMD ["..."] and specify a default command to be appended when nothing is specified. As a reference you could take a look at PR #51.

There basically I implement a **start** command where u can pass all the default arguments of server.py, as well as an help and something else. 
I would also find a nicer way of incorporating spacy...we could think of adding there a **download** command, so that the user could get spacy (en or de), as well as the .dat file for mitie...what do you think?

For reducing the footprint we could think of python-alpine as base image, maybe

**Comment by phildionne** [comment]
Thanks everyone for the help.

The image is now `386.9 MB`. Backend configuration is still missing though. You can run the it like this: `docker run -it --rm -p 5000:5000 rasa` and you can run a shell like this: `docker run -it --rm -p 5000:5000 rasa sh`

Some options for backends:
- @plauto's suggestion: with a _download_ command.
- Creating a `Dockerfile.spacy` containing an `ONBUILD` declaration that runs `pip install spacy` and `python -m spacy.en.download all`. Same logic for a `Dockerfile.mitie`
- Let the user `sh` manually and install missing dependencies for his backend

**Comment by samhavens** [comment]
To me the factors that are important when thinking about the backends:

1. Rasa doesn't really work without one of SpaCy or Mitie, so at least one must be downloaded
2. How often will SpaCy or Mitie's APIs change to the point of breaking Rasa? I assume very rarely
3. Ideally we download SpaCy or Mitie once, while frequently downloading the newest Rasa image

I think that because of 1, we want to automatically download either SpaCy or Mitie. I think `Dockerfile.spacy` is not a bad way of doing this, but it doesn't accomplish 3. But I don't think there is an easy way to accomplish 3.

**Comment by plauto** [comment]
Hi guys, please, check PR #53. The initial code submitted with this PR has been incorporated in there :)

@normanrz 
- Installing the requirements might be needed since some of them do affect functionalities (especially when we need to download data for Spacy and Mitie and use those backends). Maybe we could perform a pip install of spacy only when the user wants to download Spacy data, and the same for Mitie...I don't know though how much this could influence the footprint of the image (has to be investigated)
- Creating and switching to a user seems a good thing. I will make sure to incorporate your suggestion
- I created a repo on docker hub, but true. We do need to maintain those images and someone has to take responsibility for it.

@samhavens For now Iinstall spacy and mitie, but I don't download the modules until the user decides to do so. Technically as said before we could also perform an install of those python packages only when the user wants to download/use a specific backend.

**Pull request closed without merging**
