### PR TITLE
replaced spacy_ner with ner_crf in standard pipeline

### LINKED ISSUE #319: Create proper spacy_sklearn pipeline template that doesn't use spacy NER training
Issue: 
current spacy NER training is broken and the training functionality should be removed (not the whole component, we still want to use the build in trained spacy model to recognize default entities e.g. names or places)

Solution:
- remove training capability from `ner_spacy` (and corresponding configuration flags)
- add `ner_crf` to spacy pipeline (and to any other pipeline that uses `ner_spacy`)
- implement output merging (related to #310 and #300)

### PR DESCRIPTION
**Pull request by twerkmeister**
**Proposed changes**:
- fixes #319 

Hey wasn't to sure about what you mean by removing the training capability of the component:
1. Does this mean to completely remove the training methods: train, finetune, etc.?
2. But then it seems the training is also somehow related to the extraction of entities: 
`if spacy_nlp.entity is not None and self.fine_tune_spacy_ner:`. So I didn't remove anything yet.

@tmbo Could you take over the removal of the necessary parts given the time constraints and your knowledge of the component's internals? Happy to review the changes!

**Status**:
- [x] ready for code review
- [x] there are tests for the functionality
- [x] documentation updated
- [x] changelog updated

### CODE REVIEW

**Comment by tmbo** [comment]
done, removed the spacy ner training. please review.

**Comment by twerkmeister** [comment]
How would you now ever create a spacy ner component? There's no `__init__`, `load`, or `create` method left to initialize the component, but `process` requires and instance. :thinking:

**Comment by tmbo** [comment]
@twerkmeister there is a default implementation for `__init__` from object and `Component` provides a sane default implementation for `create` and `load`.

**Comment by twerkmeister** [comment]
Ok I am on the docs now and while I was writing I figured in how many places the spacy component was used. Also I know that some of our users have invested a lot of time and effort in generating more training data to use the fast spacy component instead of mitie which needs only little training data but is terribly slow.

The reason for this change is that version `1.8.0` training is broken. Why don't we stick with the previous spacy version where the training works @tmbo ?

**Comment by amn41** [comment]
Ok - I think dropping this is the right answer for now - users can still use 0.7 if they specifically want to train spaCy models. Then we should start a spacy-2.0-compatibility branch, because that's bringing in much bigger changes and new functionality that could be really cool for us.

**Comment by twerkmeister** [comment]
What's the benefit for us to upgrade to spacy 1.8 although this version is broken right now? For our users it will be a disadvantage, because they either have to change their workflow or stay with an older version of rasa nlu. We should have good reasons for that

**Comment by tmbo** [comment]
The reason is that the previous version was brittle and not working properly anyway ( hence the bad performance which led people switching to mitie and us to develop crf). The removal corresponds quite well to the restricted focus attitude. We added a way better alternative, and frankly I don't believe people care that much.

**Comment by twerkmeister** [comment]
I still think it's quite risky to establish a self-written and not battle-tested crf model as our new default model for training. This is due to a couple things I don't know like the reliability of spacy training, which you argue is low, and the speed and reliability of the crf training. Since you guys have more experience with the spacy component and can vouch for the crf extractor, I'd be happy to move forward nevertheless. Gonna submit the doc changes in a bit and merge

**Pull request merged**
