### PR TITLE
Optimised Dockerfile for fast, cached builds

### PR DESCRIPTION
**Pull request by angadn**

### CODE REVIEW

**Comment by twerkmeister** [comment]
@angadn yet another contribution, thanks a lot! Good idea with the caching. Can you give me a short explanation why you remove `-e .` from the requirements.txt just to add it after it being used by pip again? I am confused why the docker build process would want to change files in the original repository. Running docker build twice would lead to having two lines of `-e .` at the beginning of the build file

**Comment by angadn** [comment]
@twerkmeister the idea is to first install all dependencies without copying in our own code-base inside the container and installing our modules alongside - since Docker would then watch our files for change, and then install all dependencies afresh. In this case, you'll notice that if you try to move the `COPY` instruction to _after_ the requirements-setup, it will throw an error saying it couldn't find `setup.py` in the current directory (copy that file in isolation, and errors start cascading all the way to inside our folder-structure).

On [line 26](https://github.com/golastmile/rasa_nlu/pull/292/files#diff-3254677a7917c6c01f55212f86c57fbfR26), I concatenate the `-e .` ahead of the requirements, and ask for install again - this time, all the cached dependencies are already found, and just our modules are installed!

**Comment by twerkmeister** [comment]
Thanks for the explanation! What happens now if someone executes `setup.py` outside of the docker build file? Then the `-e` is missing unless they add it manually. Wouldn't it be better if: 1) we keep the `-e` in requirements.txt, 2) copy `requirements.txt` it into the container, 3) create a `requirements-nonlocal.txt` by cutting of the `-e` with something like `cat requirements.txt | grep -v "^-e .$" > requirements-nonlocal.txt` and 4) execute `pip install -r requirements-nonlocal.txt`. This way the non-docker build processes wouldn't be affected at all

**Comment by angadn** [comment]
Crap - to be honest, this is the first time I'm working on a Python codebase in months; makes sense, I shall make this change and update the PR as soon as I'm back at work!

**Comment by tmbo** [comment]
@angadn please let us know when you have an updated version, this is quite a neat contribution :+1:

**Comment by angadn** [comment]
Pushed update as per suggestions - testing out the build process locally now and will push fixes if necessitated

**Comment by angadn** [comment]
Not sure why 1 check is failing - can you please point me in the right direction

**Comment by tmbo** [comment]
@angadn that issue is not related to your code, merging in the latest master should resolve it.

**Comment by angadn** [comment]
Whoops - done. Hope this helps

**Comment by tmbo** [comment]
@twerkmeister please merge if you feel everything is good to go.

**Comment by twerkmeister** [comment]
Good stuff @angadn, thanks for the changes!

**Pull request merged**
