### PR TITLE
Component requirements

### LINKED ISSUE #295: ImportError: No module named flask; requirement.txt must be manually run
## Problem
**rasa NLU version** 0.8.0a11

For github installation, the README.md states
```
git clone git@github.com:golastmile/rasa_nlu.git
cd rasa_nlu
python setup.py install
```

However, when I run the program...
```
>>> python -m rasa_nlu.server
Traceback (most recent call last):
...
ImportError: No module named flask
```

The requirement install wasn't run.

I get the same issue when installing via pip, i.e. `pip install rasa_nlu`.
Must manually install requirements.txt

Minor issue for the github installation; just trips-up people who don't have much experience in python.
For the pypi installation, more of a concern.

### PR DESCRIPTION
**Pull request by tmbo**
**Proposed changes**:
- each component specifies which packages need to be installed additionally to the packages we require for normal running
- validation of installed packages previous to training a pipeline
- split requirements into `requirements.txt` (containing all essential requirements) and `dev-requirements.txt` containing all dependencies (for local dev & testing)
- fixes #295

**Status**:
- [x] ready for code review
- [ ] there are tests for the functionality
- [x] documentation updated
- [ ] changelog updated

### CODE REVIEW

**Comment by amn41** [comment]
Couple small comments: 

- why is scipy in `requirements.txt`? I'm not sure what we would use it for, but I would expect scikit-learn probably uses it
- how can I test this? what I tried:
1. create a new virtualenv
2. `pip install -r requirements.txt`
3. `python -m rasa_nlu.train -c config_mitie.json`
get a stacktrace and :
```
  File "rasa_nlu/utils/mitie_utils.py", line 43, in create
    import mitie
ImportError: No module named mitie
```
instead of the nicely formatted error message

**Comment by tmbo** [comment]
I moved the scipy dependency.

Right, that is the correct way to test it. There is a minor issue (components get created before the requirement check is done), hence when the component needs its requirement during creation it will fail before the check is done. 

Will change the order tomorrow, good catch! :+1:

**Comment by amn41** [comment]
Nice. When I try it now though the message looks like: 

```
    "> pip install {}".format(" ".join(failed_imports)))
Exception: Not all required packages are installed. To use this pipeline, run
	> pip install spacy spacy numpy numpy sklearn
```

-  remove the duplicates?
-  can we read the version numbers from `dev-requirements.txt` and display those too?

**Comment by tmbo** [comment]
@amn41 good idea!

- i fixed the duplicates
- versions are read from the `dev-requirements.txt`. the file needs to contain comments for each requirement though. but i think that is ok

**Comment by amn41** [comment]
Looks great!

**Pull request merged**
