### PR TITLE
Multitenancy

### PR DESCRIPTION
**Pull request by amn41**
addresses #36 

- server can serve multiple apps simultaneously, sharing a single `nlp` instance, if all models are spaCy and in the same language
- to use, replace `server_model_dir` in `config.json` with a json obj, e.g. `"server_model_dir":{"one":"model_XXXXX","two":"model_YYYY"}` where the keys act as aliases. Then add a `model` param to HTTP requests, e.g. `localhost:5000/parse?q=hello&model=one`
- added documentation explaining how to use
- added `test_multitenancy.py`

### CODE REVIEW

**Comment by vinvinod** [comment]
Hi @amn41 
I have modified the mitie backend to suppor the multitenancy for rasa.
My MITIE fork is at https://github.com/verloop/MITIE/tree/master
and Rasa fork is at https://github.com/verloop/rasa_nlu/commit/8073f5d1ebb012f79409832671ae0d207c2c0145

Let me know what you think about this.

**Comment by amn41** [comment]
looks cool! I'll check it out. Are there any mitie compatibility issues, e.g. could your branch in principle be merged into MITIE master?

**Comment by vinvinod** [comment]
Yes, It can be merged into MITIE master. 
But I have modified only the named_entity_extractor and text_categorizer classes for taking a total_word_feature_extractor as an input during predicting phase. I have not touched binary_relation_detector.

In the original implementaion of MITIE, get_feature_vector() of total_word_feature_extractor used the same temp variable (to avoid reallocating) for storing intermediate values. But now its allocated freshly for each function call. So these changes might not be suitable for general  MITIE users.

**Comment by vinvinod** [comment]
You can take a look at the relevant PR for MITIE https://github.com/mit-nlp/MITIE/pull/88

**Comment by vinvinod** [comment]
The PR https://github.com/mit-nlp/MITIE/pull/88 has been accepted. So now we can provide a feature extractor while doing the prediction. Its there for both `named_entity_extractor` and `text_categorizer`
I have already made the required changes for mitie interpreter and featurizer.
Its in https://github.com/golastmile/rasa_nlu/pull/149

**Comment by amr-elsehemy** [comment]
Hi I'm currently working on a developing a multi tenant application based on rasa, and I was wondering if there's more thorough documentation for this part available ? @amn41

**Comment by YazanMasafah** [comment]
Where I can find the documentation for achieving multi-tenancy?

**Pull request merged**
