### PR TITLE
Multitenancy

### PR DESCRIPTION
**Pull request by vinvinod**
Share the same feature extractor between interpreters

### CODE REVIEW

**Comment by tmbo** [comment]
Great work @vinvinod . We really want to get the whole multitenancy into rasa. To do so, it would be great if you could rebase / merge your work on the current multitenancy branch? We changed some stuff in master and currently your branch has conflicts.

**Comment by vinvinod** [comment]
Great! Sure, I will merge with the current multitenancy branch and submit.

**Comment by tmbo** [comment]
@vinvinod please let me know when you are done :)

**Comment by vinvinod** [comment]
Hey, I have already updated the PR. Couple of hours ago. I thought you
would get notified about it. I should have pinged you after that!

**Comment by tmbo** [comment]
Thanks (I saw your commits, I just wasn't sure you were done).

**Pull request merged**
