### PR TITLE
Travis pushing to docker hub after building and testing

### PR DESCRIPTION
**Pull request by twerkmeister**
**Proposed changes**:
- pushing rasa_nlu docker images to container registry

**Status**:
- [x] ready for code review
- [x] there are tests for the functionality
- [x] documentation updated
- [x] changelog updated

### CODE REVIEW

**Comment by twerkmeister** [comment]
Should we push all branches and builds or only tagged commits, like we do for pypi?

**Comment by twerkmeister** [comment]
Could need some feedback on the build process. Does it make sense to build the two docker images `minimal` and `full`, where full is the standard option that users get when they just pull the golastmile/rasa_nlu image. 

The full image contains all dev requirements plus the spacy `en` and `de` language modules and the mitie word extractor file. This way people can just start experimenting with rasa, but they would still have to link some data and or models into the container. 

The minimal image on the other hand has no specific pipeline packages installed and would allow people who know what they are doing to just install the specific requirements they need. We could also provide info on how to do that.

Are there better workflows? One improvement I would see is have some simple model in the full container, that people can try out

**Comment by amn41** [comment]
I don't feel I really have enough knowledge of docker to review the implementation, but happy to address the points. 
1. I don't think it's too important to have a pre-trained model in the full build, we have the dummy hello-goodbye model for getting the feel of the API. Giving a 'pre-trained' model will set the wrong expectation, I think users will expect it to be a good default model as opposed to an example. Since we can also train models over the HTTP api, users can then just train their first model with a single `cURL`. 
2. How big is the full image now? A couple of Gb? 
3. I think it makes sense to only push tagged commits to docker hub.

**Comment by tmbo** [comment]
I wouldn't make the default image a couple gb big due to the following assumptions:
- novice users won't generally use docker, hence the will go with a simple pypi install
- advanced users should be capable of installing further dependencies
- as long as there is a tutorial on how to use docker and install further dependencies this should be fine

**Comment by twerkmeister** [comment]
Great thanks for the feedback! Then I will change it so that the default is the minimal version again and make sure we have some documentation on how to add the components that are needed. I'll still provide a full image, too

**Pull request merged**
